name: build-and-run

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run node js script
        run: node hello.js

      - name: Run python script
        run: python script.py

      - name: Run java file
        run: |
          javac Hello.java
          java Hello
